---
meta:
  name:    imagemagick
  target:  ohio-cf
  url:     https://ci2.starkandwayne.com

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  cf:
    api_url:         ((cf-api-url))
    admin_username:  ((cf-admin-username))
    admin_password:  ((cf-admin-password))
    organization:    ((cf-organization))
    space:           ((cf-space))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: us-east-2
    access_key:  ((aws-access-key))
    secret_key:  ((aws-secret-key))

  github:
    owner:  starkandwayne
    repo:   (( concat meta.name "-buildpack" ))
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack-username))
    icon:          ((slack-icon-url))
    channel:       "#starkandwayne-buildpacks"
